#spring:
#  servlet:
#    multipart:
#      max-file-size: 1000000000000000
#  jdbc:
#    template:
#      #是以秒为单位的
#      query-timeout: 3+
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.zaxxer.hikari.HikariDataSource
    druid:
      #      initial-size:
      #      max-active:
      filters: stat,wall
      #监控页
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      #监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      filter:
        #sql监控功能
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        #防火墙配置
        wall:
          enabled: true
          config:
            drop-table-allow: false
            update-allow: false
      #开启spring监控功能
      aop-patterns: com.atroot.admin.*
  #  redis:
  #    host: r-bp180i9z2urf1gh390pd.redis.rds.aliyuncs.com
  #    port: 6379
  #    password: zyd:zYd123456
  #    client-type: lettuce
  #    redis://zyd:zYd123456@r-bp180i9z2urf1gh390pd.redis.rds.aliyuncs.com:6379
  #mybatis:
  #  check-config-location: true

  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://localhost:8888

      #  config-location: classpath:mybatis/mybatis-config.xml
  application:
    name: SpringBoot-MVC-02
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    enabled-by-default: true

    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  appName: boot-admin
  version: 2.0.1
  mavenProjectName: @project.name@
  mavenProjectID: @project.artifactId@
  mavenProjectVersion: @project.version@
